baseURL = "https://blog.canondin.cn"
title = "Canon.DinæŠ€æœ¯ v"
theme = "hugo-coder"

languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

FootnoteReturnLinkContents = "â†‘"


 # AMP ç›¸å…³
 amp = true
 # "amp-ad",
 ampElements = ["amp-analytics"]
 themeColor = "#000000"
#  adsensePublisher = "ca-pub-1886683614725279"
 googleAnalytics = "UA-112242993-2"
[params]
    author = "CanonDin"
    info1 = "ğŸ“š å­¦è€Œæ—¶ä¹ ä¹‹~"
    # info2 = "ğŸ‘¨â€ğŸ’» Full-Stack Developer"
    # info3 = "ğŸ’´ ETF Trader"
    description = "Study + Craft + Invest = CanonDin"
    keywords = "æŠ€æœ¯,ç”Ÿæ´»"
    avatarurl = "images/favicon-16x16.png"

    dateFormat = "2006-01-02"

    twitter = "abel___d_"
    github = "canondin"
#     zhihu = "improve365"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    #footercontent = ""
    hideFooter = false
    hidecredits = false
    hidecopyright = false
    since = 2020

    enableTwemoji = true
    enableGitInfo = true

    colorScheme = "auto"
    hidecolorschemetoggle = false

custom_css = ["/css/main.css"]
custom_js = ["/js/lazysizes.min.js", "/js/flying-pages.min.js", "/js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# disqusShortname = "utteranc"
[params.utteranc]
    repo = "canondin/blogUtterances"
    issue-term = "pathname"
    label = "blog"
    theme = "preferred-color-scheme"
#     theme = "github-light"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/canondin"

[[params.social]]
    name = "YouTube"
    icon = "fa fa-youtube"
    weight = 2
    url = "https://www.youtube.com/channel/UCBk8_XwPdXJdTFrnzOSL4qA"

[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/abel___d_"

[languages]

    [languages.zh-cn]
        languagename = "Chinese"
        title = "æŠ€æœ¯æ”¹å˜ç”Ÿæ´»"

        [languages.zh-cn.params]
            author = "CanonDin"
            info1 = "ğŸ“š ä¸“æ³¨æŠ€æœ¯"
            info2 = "ğŸ‘¨â€ğŸ’» åˆ†äº«å‰¯ä¸š"
            description = "å­¦è€Œæ—¶ä¹ ä¹‹"
            keywords = "Javaer,å‰¯ä¸š"

        [languages.zh-cn.menu]
#             [[languages.zh-cn.menu.main]]
#                 name = "Dashboard"
#                 weight = 1
#                 url  = "https://datastudio.google.com/reporting/6c3c6d3d-cd2f-4f8c-85e6-c06d672c445b"
            [[languages.zh-cn.menu.main]]
                name = "å…³äº"
                weight = 2
                url = "/about/"
            [[languages.zh-cn.menu.main]]
                name = "æŠ€æœ¯"
                weight = 3
                url  = "/learn/"
            [[languages.zh-cn.menu.main]]
                name = "ç”Ÿæ´»"
                weight = 4
                url  = "/life/"
            [[languages.zh-cn.menu.main]]
                name = "Tags"
                weight = 5
                url  = "/tags/"
            [[languages.zh-cn.menu.main]]
                name = "ä½œè€…"
                weight = 6
                url  = "/authors/"